# Generated by Django 6.0.5 on 2026-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
