# Generated by Django 6.0.5 on 2026-05-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_notificacao_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='lida',
        ),
    ]
